### ISSUE TITLE
JSON shouldn't require reparsing

### ISSUE THREAD

**Issue by david-a-wheeler** [boyski/pmaudit#3]
Some of the JSON values are strings that have to be parsed a second time,
in particular START:

> "START": "2019-06-15T22:44:59.301522Z (1560638699.301522)",

and the DB entries, e.g.:

~~~~
    "PREREQS": {
      "LICENSE": "1560479509.2809498,1560565909.2809498,1560638699.2983944,1560565909.2809498"
    },
~~~~

Anyone reading this has to have a JSON parser, so I suggest subdividing the data further so that atomic values are atomic.  If you're worried about space, make them a list ["value1", "value2", "value3", "value4"].  But if you have to parse the JSON anyway, there's no need to impose a second parse to actually get some of the values.

**Comment by boyski** [comment]
I think the concern was not space as in disk space but as in visual space
i.e. readability. My goal was to fit into one line per file which makes the
JSON fairly readable directly as text for debugging. Example (filenames
obfuscated because it's from the day job):

      "dir1/blah/src/blah_foo.c":
"1560095465.2652087,1560181865.2652087,1560460677.9951274,1560181865.2652087",
      "dir1/blah/src/blah_foo.h":
"1557826514.6741800,1557912914.6741800,1560460678.0261276,1557912914.6741800",
      "dir1/blah/src/blah_bar.c":
"1557219238.4547050,1557305638.4547050,1560460678.0701277,1557305638.4547050",
      "dir1/blah/src/blah_bar.h":
"1553005300.5595210,1553091700.5595210,1560460678.0571277,1553091700.5595210",
      "dir1/blah/src/blah_baz.c":
"1555779795.4407279,1555866195.4407279,1560460678.0691278,1555866195.4407279",
      "dir1/blah/src/blah_baz.h":
"1533850984.6161070,1533937384.6161070,1560460678.1371281,1533937384.6161070",

Whereas ISTR the alternatives blow out to a much less compact format which
is harder to read in vi or whatever. I agree with your general point that
the 2nd parse is inelegant (though unlikely to be a significant performance
cost IMHO) so I'm open to a change in format if it's reasonably readable as
text.

**Comment by david-a-wheeler** [comment]
Ok, but the "list of strings" isn't going to be much longer (you're already using comma-space to separate parameters).

So I'd replace:
> "1557219238.4547050,1557305638.4547050,1560460678.0701277,1557305638.4547050"

with:

> ["1557219238.4547050", "1557305638.4547050", "1560460678.0701277", "1557305638.4547050"]

... which is not much longer. Notice that I'm keeping these as strings - it's unclear that the numerical accuracy will be enough, while strings are guaranteed to work in all cases.

**Comment by boyski** [comment]
The problem is that we have no control over how JSON chooses to format
things and I believe it tends to distribute this list over 4 or 6 lines. I
may not have said it before but I originally implemented just what you
describe here and found the resulting JSON format unsatisfactory so I
deliberately hacked in this one-line string format. Probably the biggest
value in a one-line-per-file format is to be able to grep out the entry for
a given file which I have often found very convenient in debugging.

So, again, if you can find a way to get a more elegant format formatted on
one line I'm all for it but I would prefer not to have the entry for a
given file distributed over multiple lines.

David

**Comment by david-a-wheeler** [comment]
This has been resolved.
